-- Test schema: booth_voter table for local Docker MySQL
-- Only used for local testing (--local flag)

CREATE TABLE IF NOT EXISTS booth_voter (
    id varchar(26) NOT NULL,
    booth_id varchar(26) DEFAULT NULL,
    assembly_id int DEFAULT NULL,
    parliament_id int DEFAULT NULL,
    voter_id varchar(26) DEFAULT NULL,
    serial_no int DEFAULT NULL,
    kss_id varchar(26) DEFAULT NULL,
    sir_verified tinyint DEFAULT '0',
    form_submitted_to_blo int DEFAULT '0',
    blo_digitized int DEFAULT '0',
    sir_verified_by varchar(200) DEFAULT NULL,
    sir_verified_role varchar(10) DEFAULT NULL,
    sir_caste_category varchar(45) DEFAULT NULL,
    sir_political_party_id varchar(45) DEFAULT NULL,
    sir_caste_id varchar(45) DEFAULT NULL,
    is_enumiration_form_submitted tinyint DEFAULT '0',
    sir_mobile_number varchar(45) DEFAULT NULL,
    sir_latitude varchar(45) DEFAULT NULL,
    sir_longitude varchar(45) DEFAULT NULL,
    file_path text,
    sir_status varchar(50) DEFAULT NULL,
    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at datetime DEFAULT NULL,
    positive int DEFAULT '0',
    PRIMARY KEY (id),
    KEY idx_booth_voter_voter_id (voter_id),
    KEY idx_booth_voter_kss_id (kss_id),
    KEY idx_booth_voter_booth_id (booth_id),
    KEY idx_booth_voter_verified (sir_verified),
    KEY idx_booth_voter_verified_by (sir_verified_by),
    KEY idx_booth_voter_role (sir_verified_role),
    KEY idx_booth_voter_cc (sir_caste_category),
    KEY idx_booth_voter_pp (sir_political_party_id),
    KEY idx_booth_voter_caste (sir_caste_id),
    KEY idx_booth_voter_mobile_number (sir_mobile_number),
    KEY idx_booth_voter_sir_status (sir_status),
    KEY idx_booth_voter_updated_at (updated_at),
    KEY idx_bv_verified_updated_booth (sir_verified, updated_at, booth_id, voter_id),
    KEY idx_bv_verified_updated_by (sir_verified, updated_at, sir_verified_by, voter_id),
    KEY idx_bv_verified_updated (sir_verified, updated_at, sir_verified_by, booth_id, voter_id),
    KEY idx_bv_verified_uid_updated (sir_verified, sir_verified_by, updated_at, voter_id),
    KEY idx_bv_verified_booth_updated (sir_verified, booth_id, updated_at, voter_id),
    KEY idx_bv_verified_booth_updated_user (sir_verified, booth_id, updated_at, voter_id, sir_verified_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
