-- Core OLAP summary tables
-- Schema created here, data populated by Python service

-- Denormalized dimension table (single join from booth_voter + all dimensions)
CREATE TABLE IF NOT EXISTS dim_booth_voter (
    id VARCHAR(26) NOT NULL,
    booth_id VARCHAR(26) DEFAULT NULL,
    voter_id VARCHAR(26) DEFAULT NULL,
    assembly_id INT DEFAULT NULL,
    parliament_id INT DEFAULT NULL,
    serial_no INT DEFAULT NULL,
    kss_id VARCHAR(26) DEFAULT NULL,
    -- SIR fields
    sir_verified TINYINT DEFAULT 0,
    sir_status VARCHAR(50) DEFAULT NULL,
    sir_verified_by VARCHAR(200) DEFAULT NULL,
    sir_mobile_number VARCHAR(45) DEFAULT NULL,
    sir_caste_id VARCHAR(45) DEFAULT NULL,
    sir_political_party_id VARCHAR(45) DEFAULT NULL,
    file_path TEXT,
    form_submitted_to_blo INT DEFAULT 0,
    blo_digitized INT DEFAULT 0,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    -- Denormalized dimensions from booth
    state_id INT DEFAULT NULL,
    state_name VARCHAR(200) DEFAULT NULL,
    cluster_id INT DEFAULT NULL,
    cluster_name VARCHAR(200) DEFAULT NULL,
    unit_id INT DEFAULT NULL,
    unit_name VARCHAR(200) DEFAULT NULL,
    booth_name VARCHAR(200) DEFAULT NULL,
    -- Denormalized from dakavara_pa (via booth mapping)
    constituency_id INT DEFAULT NULL,
    constituency_name VARCHAR(200) DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_dbv_booth (booth_id),
    KEY idx_dbv_voter (voter_id),
    KEY idx_dbv_state (state_id),
    KEY idx_dbv_assembly (assembly_id),
    KEY idx_dbv_parliament (parliament_id),
    KEY idx_dbv_cluster (cluster_id),
    KEY idx_dbv_unit (unit_id),
    KEY idx_dbv_constituency (constituency_id),
    KEY idx_dbv_verified (sir_verified),
    KEY idx_dbv_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Summary tables

CREATE TABLE IF NOT EXISTS fact_booth_sir (
    id INT AUTO_INCREMENT PRIMARY KEY,
    booth_id VARCHAR(26) NOT NULL,
    booth_name VARCHAR(200) DEFAULT NULL,
    state_id INT DEFAULT NULL,
    state_name VARCHAR(200) DEFAULT NULL,
    parliament_id INT DEFAULT NULL,
    parliament_name VARCHAR(200) DEFAULT NULL,
    assembly_id INT DEFAULT NULL,
    assembly_name VARCHAR(200) DEFAULT NULL,
    cluster_id INT DEFAULT NULL,
    cluster_name VARCHAR(200) DEFAULT NULL,
    unit_id INT DEFAULT NULL,
    unit_name VARCHAR(200) DEFAULT NULL,
    constituency_id INT DEFAULT NULL,
    constituency_name VARCHAR(200) DEFAULT NULL,
    total_voters BIGINT DEFAULT 0,
    verified_voters BIGINT DEFAULT 0,
    active_users BIGINT DEFAULT 0,
    available_count BIGINT DEFAULT 0,
    temporary_shift_count BIGINT DEFAULT 0,
    permanent_shift_count BIGINT DEFAULT 0,
    death_count BIGINT DEFAULT 0,
    duplicate_count BIGINT DEFAULT 0,
    double_count BIGINT DEFAULT 0,
    forms_submitted_to_blo BIGINT DEFAULT 0,
    blo_digitized BIGINT DEFAULT 0,
    report_date DATE DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_fact_booth_sir (booth_id, report_date),
    KEY idx_bs_state (state_id),
    KEY idx_bs_parliament (parliament_id),
    KEY idx_bs_assembly (assembly_id),
    KEY idx_bs_cluster (cluster_id),
    KEY idx_bs_unit (unit_id),
    KEY idx_bs_date (report_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fact_booth_cubs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    booth_id VARCHAR(26) NOT NULL,
    booth_name VARCHAR(200) DEFAULT NULL,
    booth_part_no VARCHAR(100) DEFAULT NULL,
    state_id INT DEFAULT NULL,
    state_name VARCHAR(200) DEFAULT NULL,
    parliament_id INT DEFAULT NULL,
    parliament_name VARCHAR(200) DEFAULT NULL,
    constituency_id INT DEFAULT NULL,
    constituency_name VARCHAR(200) DEFAULT NULL,
    cluster_id INT DEFAULT NULL,
    cluster_name VARCHAR(200) DEFAULT NULL,
    unit_id INT DEFAULT NULL,
    unit_name VARCHAR(200) DEFAULT NULL,
    tehsil_id INT DEFAULT NULL,
    tehsil_name VARCHAR(200) DEFAULT NULL,
    panchayat_id INT DEFAULT NULL,
    panchayat_name VARCHAR(200) DEFAULT NULL,
    local_election_body_id INT DEFAULT NULL,
    local_election_body_name VARCHAR(200) DEFAULT NULL,
    mobile_count BIGINT DEFAULT 0,
    caste_count BIGINT DEFAULT 0,
    party_count BIGINT DEFAULT 0,
    forms_count BIGINT DEFAULT 0,
    available_count BIGINT DEFAULT 0,
    temporary_shift_count BIGINT DEFAULT 0,
    permanent_shift_count BIGINT DEFAULT 0,
    death_count BIGINT DEFAULT 0,
    duplicate_count BIGINT DEFAULT 0,
    double_count BIGINT DEFAULT 0,
    report_date DATE DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_fact_booth_cubs (booth_id, report_date),
    KEY idx_bc_state (state_id),
    KEY idx_bc_parliament (parliament_id),
    KEY idx_bc_constituency (constituency_id),
    KEY idx_bc_cluster (cluster_id),
    KEY idx_bc_unit (unit_id),
    KEY idx_bc_date (report_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fact_voter_location (
    id INT AUTO_INCREMENT PRIMARY KEY,
    location_id INT NOT NULL,
    location_type ENUM('state','parliament','assembly','constituency','cluster','unit','booth','tehsil','panchayat','town') NOT NULL,
    state_id INT DEFAULT NULL,
    state_name VARCHAR(200) DEFAULT NULL,
    parliament_id INT DEFAULT NULL,
    parliament_name VARCHAR(200) DEFAULT NULL,
    assembly_id INT DEFAULT NULL,
    assembly_name VARCHAR(200) DEFAULT NULL,
    constituency_id INT DEFAULT NULL,
    constituency_name VARCHAR(200) DEFAULT NULL,
    total_voters BIGINT DEFAULT 0,
    publication_date_id INT DEFAULT 42,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_fact_voter_loc (location_id, location_type, publication_date_id),
    KEY idx_vl_state (state_id),
    KEY idx_vl_parliament (parliament_id),
    KEY idx_vl_assembly (assembly_id),
    KEY idx_vl_constituency (constituency_id),
    KEY idx_vl_type (location_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
